---
- name: Restore playbook.yml
  hosts: all
  tasks:
    - name: Remove the packages
      yum:
        name:
          - httpd
          - mariadb-server
          - mutt
          - tree
        state: absent