---
- name: Restore playbook.yml
  hosts: webserver
  tasks:
    # 1) /etc/ansible/facts.d 디렉토리 삭제 (file)
  - name:
    file:
      path: /etc/ansible/fact.d
      state: absent

    # 2) 웹 패키지 종료 - httpd (service)
  - name:
    service:
      name: httpd
      state: stopped


    # 3) 웹 패키지 삭제 - httpd (yum)
  - name:
    yum:
      name: httpd
      state: absent
