---
- name: 패키지 설치 {{ pkg_fw }}
  yum: 
    name: "{{ pkg_fw }}"
    state: latest

- name: 서비스 기동 - {{ svc_fw }}
  service:
    name: "{{ svc_fw }}"
    state: started
    enabled: yes
  
- name: 방화벽 서비스 등록 - {{ fw_webs}}
  firewalld:
    service:  "{{ item }}"
    permanent: yes
    immediate: yes
    state: enabled
  with items: "{{ fw_webs }}"