---
- name: 웹페이지 테스트
  hosts: localhost
  gather_facts: no
  become: false
  tasks: 
    - name: 웹서버 연결 테스트  - {{ url }}
      uri: 
        url: "{{ url }}"
        return_content: yes
        status_code: 200


