---
- name: /etc/named.conf 파일 생성
  copy:
    src: files/named.conf.template
    dest: /etc/named.conf
    owner: root
    group: named
    mode: '0640'
  notify: restart named

- name: /etc/named.rfc1912.zones 파일 생성
  copy:
    src: files/named.rfc1912.zones.template
    dest: /etc/named.rfc1912.zones
    owner: root
    group: named
    mode: '0640'
  notify: restart named



- name: /var/named/named.ca  파일 생성
  template:
    src: templates/named.ca.j2
    dest: /var/named/named.ca
    owner: root
    group: named
    mode: '0640'
  notify: restart named

- name: /var/named/com.zones 파일 생성
  template:
    src: templates/com.zone.j2
    dest: /var/named/com.zone
    owner: root
    group: named
    mode: '0640'
  notify: restart named

- name: /var/named/com.rev 파일 생성
  template:
    src: templates/com.rev.j2
    dest: /var/named/com.rev
    owner: root
    group: named
    mode: '0640'
  notify: restart named
